name: PlatformIO

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare output directories
      run: |
        rm -fdr ${{ github.workspace }}/bin
        mkdir ${{ github.workspace }}/bin
    - name: Build
      run: |
        docker run \
        -v ${{ github.workspace }}:/opt/workspace \
        --workdir /opt/workspace \
        infinitecoding/platformio-for-ci \
        /bin/bash -c "platformio run"
